# Homebrewのアップデートを行う
update

# Formulaのアップブレードを行う
upgrade

# リポジトリの追加を行う
tap caskroom/cask
tap caskroom/versions
tap peco/peco
tap ariela/ariela-cask

# パッケージのインストール
install zsh
install git
install wget
install md5sha1sum
install brew-cask
install peco

# App Storeで購入している物は未記載
# (cask) アプリケーションのインストール
cask install wacom-tablet || true
cask install keyremap4macbook || true
cask install vlc || true
cask install google-chrome || true
cask install flash || true
cask install quicksilver || true
cask install totalfinder || true
cask install iterm2 || true
cask install sourcetree || true
cask install dropbox || true
cask install blueharvest || true
cask install cyberduck || true
cask install coteditor || true
cask install java7 || true
cask install netbeans-php || true
cask install virtualbox || true
cask install vagrant || true
cask install vagrant-manager || true
cask install notifyr || true
cask install qlcolorcode || true
cask install qlstephen || true
cask install qlmarkdown || true
cask install qlprettypatch || true
cask install quicklook-json || true
cask install quicklook-csv || true

# (self) アプリケーションのインストール
cask install atok-passport || true
cask install sublime-text3 || true
cask install clipstudio-paint || true

# 古いバージョンを取り除く
cleanup
